### ISSUE TITLE
Encrypted strings from 2.0 incompatible with 3.0 and 4.0

### ISSUE THREAD

**Issue by ogomez92** [MauriceButler/cryptr#10]
Hello.
Encrypted stirngs from verison 2.0 are not compatible with version 3.
what is wrong?
I am trying to decrypt a string encoded into a file and this has always worked until I updated to version 3 and then to version 4.
Cryptr 2 seems to be incompatible with the latest version of Electron.

Is there a workaround for this? I need to be able to open old files with the latest versions of cryptr if I want to upgrade Electron.
Thanks.

**Comment by MauriceButler** [comment]
Version 2 uses a different default cipher than version 3, hence the major version change.

If you have data encrypted using version 2 I suggest you use version 2 to decrypt them.

I would then suggest you upgrade to the latest version 5 to re encrypt them.

**Comment by ogomez92** [comment]
Sure that sounds good, problem it's saved data from games that I'm
encrypting, oh well.
No problem I'll figure it out thanks
