### ISSUE TITLE
Error using cryptr in react-native , getting error crypto does not exist in haste module

### ISSUE THREAD

**Issue by ctrljs** [MauriceButler/cryptr#12]
error: bundling failed: Error: Unable to resolve module `crypto` from `D:\mobile_new_1503\node_modules\cryptr\index.js`: Module `crypto` does not exist in the Haste module map

**Comment by rajat-np** [comment]
The crypto module is a built-in Node module; React Native runs JS on JavaScriptCore (when on the device or simulator) and on Chrome itself (when using Chrome debugging), so modules that depend on built-in Node.js modules won't work. 

Head over to [https://stackoverflow.com/questions/36415157/twilio-react-native-unable-to-resolve-module-crypto](this) for a possible hack solution.

**Comment by rajat-np** [comment]
The crypto module is a built-in Node module; React Native runs JS on JavaScriptCore (when on the device or simulator) and on Chrome itself (when using Chrome debugging), so modules that depend on built-in Node.js modules won't work. 

Head over to [this](https://stackoverflow.com/questions/36415157/twilio-react-native-unable-to-resolve-module-crypto) for a possible hack solution.
