### ISSUE TITLE
Same function returns different results

### ISSUE THREAD

**Issue by davehowson** [MauriceButler/cryptr#14]
I have the following function in two different ReactJS applications,

```
const encryptedId = id => {
  try {
    const Cryptr = require('cryptr');
    const cryptr = new Cryptr("SECRET");
    const encryptedString = cryptr.encrypt(id);
    console.log("SECRET", id, encryptedString)
    return encryptedString;
  } catch (e) {
    return null;
  }
};
```

Both of these functions are identical yet one produces 
`SECRET 299 6fde79bed10ed3e5f3191902d2fec0797b1703` 
which has 38 digits and the other

`SECRET 299 2971f81ed84ee618f1b84e`
which only has 22.

Why is there such a difference?
Both of these applications use `"cryptr": "^4.0.0"`

**Comment by MauriceButler** [comment]
There are 3 different versions of this module that could match the semver range of `"cryptr": "^4.0.0"`

[v4.0.0](https://github.com/MauriceButler/cryptr/releases/tag/v4.0.0)
[v4.0.1 (Deprecated)](https://github.com/MauriceButler/cryptr/releases/tag/v4.0.1)
[v4.0.2](https://github.com/MauriceButler/cryptr/releases/tag/v4.0.2)

I assume the 2 different applications are using a different version of the module.

I suggest you either lock to a specific version or update to the latest version of the module [v6.0.0](https://github.com/MauriceButler/cryptr/releases/tag/v6.0.0)
