### ISSUE TITLE
How to check string is encrypted or not ?

### ISSUE THREAD

**Issue by jaydevvaghela943** [MauriceButler/cryptr#15]
Hello Sir,
I have a script that have some data are encrypted or some data are not encrypted.
When I try to decrypt data its work on new data but some old data are not encrypted. So How I checked this is encrypted or not. So I can easily decrypt the value and not break my code...

Please Help me ASAP.

Thanks & Regards,
Jay

**Comment by MauriceButler** [comment]
You cant tell if a string is encrypted or not just from the string itself. My only suggestion would be to try to decrypt it, if it fails then you know is wasn't encrypted...
