### ISSUE TITLE
Not working with Node v13 (Buffer with odd number of bytes)

### ISSUE THREAD

**Issue by GreenLong** [MauriceButler/cryptr#17]
It seems like not working with Node v13. I get the error in example from doc:

> TypeError [ERR_INVALID_ARG_VALUE]: The argument 'encoding' is invalid for data of length 11. Received 'hex'

But if I use for encrypting text with an even number of characters - it's ok.

Maybe is something changed in update method. If pass encrypted as string it will be ok. Buffer with odd number of bytes - error.

`return decipher.update(encrypted.toString('hex'), 'hex', 'utf8') + decipher.final('utf8');`

No error on v10.16.3, v12.8.0.

**Comment by MauriceButler** [comment]
Oh fun! :disappointed: 

Looks like this issue in node https://github.com/nodejs/node/issues/29786

Ill keep an eye on it and see what can be done.
