### ISSUE TITLE
issue while decrypt password

### ISSUE THREAD

**Issue by Hspharwinder** [MauriceButler/cryptr#19]
cryptr.decrypt('cc70a01ea977c3d5e9626396b84cb718339d7a30669341e63891919ddeeed48d35b70dc4d48838545eac6f92241726cceba0')
Error: Invalid IV length

![image](https://user-images.githubusercontent.com/40883035/69716883-04cf8500-1131-11ea-8195-a6f24c38065d.png)

**Comment by MauriceButler** [comment]
I can only assume you are using a different version of the module to decrypt then you did to encrypt it.

Ensure you are using the same version which will mean the same algorithm and method of encryption / decryption.

Also, if that is actualy a password you are working with then this is the wrong library for that.

**DO NOT USE THIS MODULE FOR ENCRYPTING PASSWORDS**
