### ISSUE TITLE
How can i use this package in my angular app?

### ISSUE THREAD

**Issue by fahadsubzwari924** [MauriceButler/cryptr#20]
I want to use this package in my angular app. I installed this package in angular app and then require lke this

    `declare var require : any;

     import * as Cryptr from 'cryptr';
     const cryptr = new Cryptr(my-phrase);`

But it throws an error like this

`ERROR in ./node_modules/cryptr/index.js
Module not found: Error: Can't resolve 'crypto' in 'D:\FreelanceProjects\ReferlingProject(Melvin)\referral-sow\node_modules\cryptr'`

How can  i resolve this issue?

**Comment by MauriceButler** [comment]
In its current for this is a server side module as like you pointed out it depends on the node core crypto module. 

It will not run in the browser.
