### ISSUE TITLE
Can i use this module in password encryption?

### ISSUE THREAD

**Issue by izaanjahangir** [MauriceButler/cryptr#21]
Is it secure to use this library for password encryption? My use case is different the password i am storing is actually an API key. so i can't go with one way HASH. i want to store the password in encrypted form in the database and later on decrypt it and send it to the API

**Comment by MauriceButler** [comment]
I suggest you do some research into `aes-256-gcm` as this is the algorithm used by this module.

And then use that information, along with your attack vector risk analysis to determine if `aes-256-gcm` would suit your requirements or not.
