### ISSUE TITLE
Invalid IV length

### ISSUE THREAD

**Issue by enoler** [MauriceButler/cryptr#22]
Hello!

I recently updated from 4.0.2 to 6.0.1 and I started to have this issue (Invalid IV length) always that I try to decrypt a value.

Is there something that I can do for solve this problem without changing my secret?

**Comment by kerbe** [comment]
@enoler I don't think you can solve that problem, if you want to keep using old encrypted data.
In this commit:
https://github.com/MauriceButler/cryptr/commit/419cc34027fee1523d8d353e7f1e31fd08ff2ef9
which is version 6.0.0, there has been change in algorithm: aes-256-ctr -> aes-256-gcm, and I think that key hash has also changed from sha256 -> sha512.

So either you need to downgrade to 5.x version and prevent upgrading, or use old version to do decrypting, and then encrypt again with new version.

**Comment by MauriceButler** [comment]
Yep, the major version change is breaking and you wont be able to decrypt values encrypted with an old algorithm.

I would suggest either updating your old values in bulk and then upgrade or have some handling in your code to determine the version used for encryption and change process based on that.
