### ISSUE TITLE
Async to speed up execution

### ISSUE THREAD

**Issue by zicodes** [MauriceButler/cryptr#24]
Hello there,
just wanted to note that by simply changing:
`function Cryptr(secret) {`
to
`async function Cryptr(secret) {`
has yielded me almost 3x performance.
For anyone doing CPU intensive tasks in Node - async function is your friend.

**Comment by vorasudh** [comment]
@zicodes, It is a nice idea. I tried to use async, but it says `_utils_cryptr_js__WEBPACK_IMPORTED_MODULE_8___default.a is not a constructor`. Can you tell me what else did you change?

Info: I am using it in a React project.

**Comment by MauriceButler** [comment]
@zicodes Im pretty sure whatever it is you are doing is not actually helping you the way you think it is...

Adding the `async` keyword to a constructor in not valid, and even if it was, the overhead of a promise wrapping the sync code will most certainly slow things down not make it faster.

I suggest you double check you are getting the encrypted results you think you are.
