### ISSUE TITLE
Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by telltokichu** [MauriceButler/cryptr#26]
I have to use cryptr in my React App but I'm getting this error - PFA
Help.
Thanks in advance.

<img width="1434" alt="Screenshot 2020-04-29 at 4 43 56 PM" src="https://user-images.githubusercontent.com/25656723/80590165-0fbc7780-8a39-11ea-9a9a-6358b4bb909d.png">

**Comment by MauriceButler** [comment]
cryptr is just a wrapper around the node core crypto module.

Which is not available in the browser. 

It is not designed to work in a browser or react application.
