### ISSUE TITLE
How to decrypt using c#

### ISSUE THREAD

**Issue by sathis810** [MauriceButler/cryptr#28]
Hi,
Encryption and descryption working. but i need to encrypt from javascript and decrypt to c# code. is this possible?

**Comment by MauriceButler** [comment]
Hi @sathis810 

Short answer is yes, its possible. The encryption is a standard algorithm so it can be decrypted in other languages.

However... While I dabble, I am by no means a C# expert. From a bit of googling it looks like the .Net core does not include an implementation of AES so you will need a library such as Bouncy Castle.

Seems this might point you in the right direction https://github.com/lukemerrett/Bouncy-Castle-AES-GCM-Encryption

The other thing to note is for simplicity and portability, `Cryptr` prepends the salt, iv and authentication tag to the result, so something like the above approach will need to do the same manipulations as `Cryptr`

If you do come up with a working solution I would be very interested to see it!
