### ISSUE TITLE
Invalid initialization vector

### ISSUE THREAD

**Issue by TheCuteFoxxy** [MauriceButler/cryptr#31]
I am utilizing a database to store encryption keys on a per-user basis, however when trying to masquerade as a user for testing I get the Invalid initialization vector even though a valid and correct encryption key is being returned from the database.
```
    if (command === 'sudo') {
        if (args.length < 2) return message.channel.send('Missing Paramater(s).')
        if (message.author.id !== '641795527444529152') return;
        if (args[1].toLowerCase() !== 'encrypt' && args[1].toLowerCase() !== 'decrypt') return message.channel.send('Missing Paramater(s).')
        let key = await encryption_keys.get(args[0])
        if (key === undefined) return message.channel.send('No encryption key found for that user.')
        
        if (args[1].toLowerCase() === 'decrypt') {
        console.log(key)
        let toDecrypt = message.content.split(' ').slice(1).join(' ')
        if (toDecrypt.length < 1 || args.length < 3) return message.channel.send('Data to decrypt must be at least 1 character in length.')
        if (toDecrypt.length > 750) return message.channel.send('Data to decrypt cannot be more than 750 characters in length.')
        let cryptr = new Cryptr(key);
        let decryptedString = cryptr.decrypt(toDecrypt);
        message.channel.send('**Data Decrypted**\n' + decryptedString)    
        }

**Comment by MauriceButler** [comment]
I don't think I can be of much help to you, but maybe I can point you in the right direction.

The initialization vector (IV) is stored in the result from the `encrypt` call not the key so the key you are storing is potentially fine.

You can see [here](https://github.com/MauriceButler/cryptr/blob/master/index.js#L34) that the result includes the salt, iv, authTag and the encrypted message.

I am assuming that the encrypted message which you have called `toDecrypt` is invalid in some way, either generated with a different cipher, older version or is in the wrong format.

You can see [here](https://github.com/MauriceButler/cryptr/blob/master/index.js#L51) that the `decrypt` method gets the IV from the passed in string value and uses it to call `createCipheriv`.

The only way for it to return that message is for the IV to be `null`, `''`, or a zero length buffer.

You can see the tests for that in the node source code [here](https://github.com/nodejs/node/blob/e46c680bf2b211bbd52cf959ca17ee98c7f657f5/test/parallel/test-crypto-cipheriv-decipheriv.js#L162)

Hope that helps you track down the issue.

**Comment by margani** [comment]
For me the issue was the decryption of an empty string.
