### ISSUE TITLE
Deno port based on Web Crypto API ?

### ISSUE THREAD

**Issue by tianalemesle** [MauriceButler/cryptr#36]
Hello,

Would you be interested in making a [Deno](https://deno.land/) port of `cryptr` possibly based on the [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) ?

Thanks

**Comment by MauriceButler** [comment]
HI,

I have 0 experience with Deno, but if this is something you want to take on, feel free to use this lib as a starting point.

**Comment by DjDeveloperr** [comment]
@MauriceButler Would a PR be welcome to use make use of Web Crypto instead of Node's crypto module? That way it can work on Node.js, Deno and Browser.

**Comment by MauriceButler** [comment]
I dont really want to make this work in the browser, as client side crypto is a bad idea in my opinion.

But like I said, you are more than welcome to fork and change things if you would like to do that yourself.

**Comment by DjDeveloperr** [comment]
Oh okay, that's understandable - appreciate the response.
I've actually already made a port based on Web Crypto API: https://github.com/DjDeveloperr/deno_cryptr

**Comment by KaKi87** [comment]
> I dont really want to make this work in the browser

Actually, this is about making it work in Deno, which works with browser APIs.
> client side crypto is a bad idea in my opinion

Why would it ?
Client-side crypto allows the user to encrypt data that servers will be able store with zero access.
That's now [PrivateBin](https://privatebin.info/) (a privacy-friendly Pastebin alternative) works, for example.
