### ISSUE TITLE
secret error

### ISSUE THREAD

**Issue by Elue-dev** [MauriceButler/cryptr#43]
i'm building a node js app with typescript and i keep getting this error when i'm trying to use cryptr : Cryptr: secret must be a non-0-length string

When i hard code the secret it works fine. The error is NOT from my .env because if i log process.env.CRYPTR_KEY to the connsole, it logs it properly. please help with this issue

**Comment by Elue-dev** [comment]
So i solved this issue but declaring a variable outside my controller function, then reassigned the variable with the new Cryptr object. as opposed to defining the enter object at the top level.
**Image descriptions below:**

<img width="1044" alt="Screen Shot 2022-12-23 at 00 50 10" src="https://user-images.githubusercontent.com/79481288/209244523-644863c9-bdb4-462b-9593-440f40d4c17c.png">

**As opposed to doing it like this:**

<img width="1031" alt="Screen Shot 2022-12-23 at 00 51 15" src="https://user-images.githubusercontent.com/79481288/209244566-9ec12970-3319-433b-a7e0-f68066813866.png">

**Comment by MauriceButler** [comment]
I dont know what to say other than you are 100% not passing the correct thing into the constructor.

The code is pretty straight forward 

```javascript
if (!secret || typeof secret !== 'string') {
    throw new Error('Cryptr: secret must be a non-0-length string');
}
 ```
 
 I am assuming from your text you are setting `process.env.CRYPTR_KEY` and expecting it to work.
 Are you actually passing that into the constructor?
 
 Something like
  
 ```javascript
 new Cryptr(process.env.CRYPTR_KEY)
 ```
