### ISSUE TITLE
Add TypeScript types in in this package

### ISSUE THREAD

**Issue by apstanisic** [MauriceButler/cryptr#45]
Currently there is external `@types/cryptr` package, but it's stuck on version 4. 

It would be safer if this package had built in types, since then they could not get out of the sync. Currently [types say](https://www.npmjs.com/package/@types/cryptr?activeTab=explore) that this module uses `ctr`, which is incorrect.
Types for this module are simple, I can create PR if needed.

I think that this is not a breaking change and that only `types` property can be added to `package.json`. It might be considered breaking if user is currently passing invalid data and using typescript for compiling.

**Comment by MauriceButler** [comment]
If you would like to PR some type definitions, and this will make your usage of this module better, I would be more than happy to merge it.

However, so far I have managed to pretty much ignore TypeScript in my career, and have no plans to add them myself :)
