### ISSUE TITLE
Error: Cryptr: secret must be a non-0-length string

### ISSUE THREAD

**Issue by alfi-dim** [MauriceButler/cryptr#49]
Need help, i'm using .env.local to store the secret key, and it's showing the error, i'd try console.log it, it showing the key, and this is my code

```
import Cryptr from 'cryptr';

const key = process.env.SECRET_KEY;
console.log(key); // 539a59272fdae31ea94470b16e5....
const cryptr = new Cryptr(key); // this cause Error: Cryptr: secret must be a non-0-length string
export default function encrypt(payload) {
  return cryptr.encrypt(payload);
}
```

thanks!

**Comment by MauriceButler** [comment]
The code that throws that error is very basic. For it to fail, the secret you are passing need to have a non falsey value and be typeOf string. 

On face value your const `key` above seem to have a valid value in it, so I can't be of much more help than that I am afraid.

[link to code](https://github.com/MauriceButler/cryptr/blob/master/index.js#L11)

``` javascript
    if (!secret || typeof secret !== 'string') {
        throw new Error('Cryptr: secret must be a non-0-length string');
    }
```
