### ISSUE TITLE
Hey, Is this still useful as the methods createCipher and createDecipher are deprecated?

### ISSUE THREAD

**Issue by WebbizAdmin** [MauriceButler/cryptr#5]
Do you think to update the package?

**Comment by WebbizAdmin** [comment]
For anyone looking to upgrade , I have used this instead, maybe you guys can give some feedback on it??
`
const encryptPass =  (data) =>  {
    const iv = new Buffer(16);
    const encrypt = crypto.createCipheriv('aes256', process.env.MT4_KEY, iv)
    let result = encrypt.update(data, 'utf-8', 'hex');
        result += encrypt.final('hex');
    return result;
  }
const decryptPass =   (data) => {
    const iv = new Buffer(16);
    const decrypt = crypto.createDecipheriv('aes256', process.env.MT4_KEY, iv)
    let result = decrypt.update(data, 'hex', 'utf-8');
        result += decrypt.final('utf-8');
    return result;
  },
`

**Comment by MauriceButler** [comment]
Hi @WebbizAdmin, thanks for the nudge, I have been meaning to update this for a while.

Updates have been made and release as version [4.0.0](https://github.com/MauriceButler/cryptr/releases/tag/v4.0.0)

As for your code above, ignoring the environment variable, I believe there are a couple of issues you are going to have. 

- Your `iv` is an uninitialised buffer, meaning its always the same. (Worse in node < 6 its an [uninitalised Buffer](https://nodejs.org/docs/latest-v10.x/api/buffer.html#buffer_new_buffer_size)) This means you are basicly rendering it useless. 
- You dont return you `iv` in the result, meaning it cant be used in the decryption at a later date (currently works as you create an uninitialised Buffer again)


For comparison my implementation is [here](https://github.com/MauriceButler/cryptr/blob/v4.0.0/index.js#L14)

**Comment by WebbizAdmin** [comment]
Hey @MauriceButler, thank you for feedback, I had used crypto.randomBytes(16) but had errors, it must be the to hex and slice. I will try thins now replacing new Buffer. Thank again
