### ISSUE TITLE
Can't resolve 'crypto' in 'D:\username\node_modules\cryptr'

### ISSUE THREAD

**Issue by Thomas0921** [MauriceButler/cryptr#9]
I am planning to use this in my angular front end to encrypt some data, but I can't require it. it shows me this error. 

> Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i @types/node`.

I have done these steps
`npm install @types/node --save-dev`
and include this in tsconfig.json
`{
    "compilerOptions": {
        "types": ["node"]
    }
}`

but still fail, could anyone let me know how to use cryptr in my angular front end typescript? many thanks

**Comment by Thomas0921** [comment]
Update

I have a new error here, more related to the packages

> Error: Can't resolve 'crypto' in 'D:\username\ProjectR\website\node_modules\cryptr'

do you guys have any idea?

**Comment by Thomas0921** [comment]
Problem solved, here is the link of the solution

[https://github.com/ethereum/web3.js/issues/1555#issuecomment-388113909](url)

**Comment by ctrljs** [comment]
> Problem solved, here is the link of the solution
> 
> [https://github.com/ethereum/web3.js/issues/1555#issuecomment-388113909](url)

where is the solution ?? Can you please provide link again or the solution here directly
